// Palabras que llevan a una categoría inicial (ADR 0015). Se buscan por ID, así que siguen
// funcionando si el usuario renombra la categoría. Van sin acentos ni mayúsculas.

export const CATEGORY_SYNONYMS: Readonly<Record<string, readonly string[]>> = {
  seed_comida: [
    'super',
    'supermercado',
    'chino',
    'almacen',
    'verduleria',
    'carniceria',
    'panaderia',
    'fiambreria',
    'kiosco',
    'almuerzo',
    'cena',
    'desayuno',
    'merienda',
    'comida',
    'delivery',
    'pedidosya',
    'rappi',
    'restaurante',
    'resto',
    'rotiseria',
    'pizza',
    'empanadas',
    'cafe',
    'facturas',
  ],
  seed_transporte: [
    'colectivo',
    'bondi',
    'subte',
    'tren',
    'sube',
    'taxi',
    'remis',
    'uber',
    'cabify',
    'didi',
    'nafta',
    'combustible',
    'estacionamiento',
    'peaje',
  ],
  seed_servicios: [
    'luz',
    'gas',
    'agua',
    'internet',
    'wifi',
    'telefono',
    'celular',
    'cable',
    'expensas',
    'abl',
  ],
  seed_ocio: [
    'cine',
    'teatro',
    'recital',
    'entradas',
    'salida',
    'bar',
    'boliche',
    'birra',
    'cerveza',
    'netflix',
    'spotify',
    'juego',
    'juegos',
  ],
  seed_salario: ['sueldo', 'salario', 'aguinaldo', 'quincena'],
  seed_otros_ingresos: ['regalo', 'reintegro', 'devolucion', 'venta'],
};

/** Índice inverso: palabra → ID de la categoría inicial. */
export const SYNONYM_INDEX: ReadonlyMap<string, string> = new Map(
  Object.entries(CATEGORY_SYNONYMS).flatMap(([id, words]) => words.map((w) => [w, id] as const)),
);
